### PR TITLE
Fix story tags not being rendered in preview

### PR DESCRIPTION
**Pull request by sohaibbhatti**
https://github.com/lobsters/lobsters/issues/522

Accessing tags from a story involves a database query. For records that haven't been persisted yet, resorting to fetch tags from the instantiated taggings.

### CODE REVIEW

**Comment by pushcx** [comment]
It's strange to me that the unsaved associated tags are not available through the usual `.tags`, do you know why that is? And were you able to track down why this broke?

**Comment by sohaibbhatti** [comment]
I'd looked at a commit that was for resolving a n+1 query problem which caused the issue to pop up. 7dfbbea3b542e431161d662ee889131c3a64d5fc 

To reproduce
```
git checkout 7dfbbea3b542e431161d662ee889131c3a64d5fc^1  #wouldnt exist
git checkout 7dfbbea3b542e431161d662ee889131c3a64d5fc #will exist
```

I believe its because of a has_many :through association, so I'm assuming a query is always needed, i.e. we can access taggings from a built story, but not tags as it needs to go through taggings.(plus there is a default order scope on the association as well). I'll look into it further

**Comment by pushcx** [comment]
Ah, so the issue is that `StoryController#story_params` is setting the tags as `Story#tags_a=` which uses `taggings` instead of `tags`, so Rails doesn't create objects in `tags` for the `has_many :through` to use. Can you edit `tags_a` to maintain that usual behavior? That's a lot more maintainable than knowing not to a custom method instead of one association of one model before it's persisted.

**Comment by sohaibbhatti** [comment]
Definitely! I'll do it in a bit!

**Comment by pushcx** [comment]
Thanks for running this one down and finding a clean fix that maintains Rails idioms. I've just deployed your fix.

**Comment by sohaibbhatti** [comment]
Thank you for being on it with the reviews :)
Off topic, but whenever you have a moment could you have a look at the comment in  https://github.com/lobsters/lobsters/issues/525

**Pull request merged**
