### PR TITLE
Update _form.html.erb for tags_controller

### LINKED ISSUE #633: creating tags fails
```
Jan 15 10:59:14 tilde bundle[2681]: I, [2019-01-15T10:59:14.604804 #2681]  INFO -- : [d4ab831e-3bf6-4131-a0bc-757418c84d33] Started POST "/tags" for 97.86.94.26 at 2019-01-15 10:59:14 -0500
Jan 15 10:59:14 tilde bundle[2681]: I, [2019-01-15T10:59:14.606144 #2681]  INFO -- : [d4ab831e-3bf6-4131-a0bc-757418c84d33] Processing by TagsController#create as HTML
Jan 15 10:59:14 tilde bundle[2681]: I, [2019-01-15T10:59:14.606279 #2681]  INFO -- : [d4ab831e-3bf6-4131-a0bc-757418c84d33]   Parameters: {"utf8"=>"✓", "authenticity_token"=>"89J5Lq9mgDROTD/3f4pNkmlGqxs1u6TMsYRQ40KaTFeniltpb1ErR6yiHDsIl5UQYvwly2RWGg5Q3Yb/gUsfdg==", "tag"=>"test", "description"=>"test", "privileged"=>"0", "is_media"=>"0", "inactive"=>"0", "hotness_mod"=>"1", "commit"=>"Create Tag"}
Jan 15 10:59:14 tilde bundle[2681]: I, [2019-01-15T10:59:14.609650 #2681]  INFO -- : [d4ab831e-3bf6-4131-a0bc-757418c84d33]   Logged in as user 1 (ben)
Jan 15 10:59:14 tilde bundle[2681]: I, [2019-01-15T10:59:14.615924 #2681]  INFO -- : [d4ab831e-3bf6-4131-a0bc-757418c84d33]   Traffic level: 1
Jan 15 10:59:14 tilde bundle[2681]: I, [2019-01-15T10:59:14.624115 #2681]  INFO -- : [d4ab831e-3bf6-4131-a0bc-757418c84d33] Completed 500 Internal Server Error in 18ms (ActiveRecord: 4.9ms)
Jan 15 10:59:14 tilde bundle[2681]: F, [2019-01-15T10:59:14.625467 #2681] FATAL -- : [d4ab831e-3bf6-4131-a0bc-757418c84d33]
Jan 15 10:59:14 tilde bundle[2681]: F, [2019-01-15T10:59:14.625639 #2681] FATAL -- : [d4ab831e-3bf6-4131-a0bc-757418c84d33] NoMethodError (undefined method `permit' for "test":String):
Jan 15 10:59:14 tilde bundle[2681]: 127.0.0.1 - - [15/Jan/2019:10:59:14 EST] "POST /tags HTTP/1.0" 500 0
```

checked with @pushcx about this on irc and he thinks it's related to `form_with`.

it's happening [somewhere in here](https://github.com/lobsters/lobsters/blob/master/app/controllers/tags_controller.rb#L51-L58)

### PR DESCRIPTION
**Pull request by svintbel**
Small PR to fix #633 
because "mode:" is an invalid function for method form_with

### CODE REVIEW

**Comment by pushcx** [comment]
Hey, thanks for running down this bug and sharing a fix. I figured I'd be starting my day doing that, so it's really nice to wake up to it done. :)

**Comment by svintbel** [comment]
Not at all, can u send me an invitation?

**Comment by alanpost** [comment]
I'd be happy to send you an invitation svintbel.  I'll need your email address, will you write me so I have yours?

**Comment by svintbel** [comment]
svintbel@gmail.com
Thanks!)

**Pull request merged**
