### PR TITLE
Rubocop

### PR DESCRIPTION
**Pull request by pushcx**
I'm adding rubocop to enforce style issues to save human attention (and patience) in code reviews. The default config found 4,849 offenses and this branch will be merged when there are zero.

Like everybody I have opinions on style issues, but my preferred style for any codebase is whatever the codebase is already doing. With that in mind, I'm configuring [cops](https://rubocop.readthedocs.io/en/latest/cops/#available-cops) to enforce the common usage and then tweaking outliers to match, eg. 988aa22 and fda61bb.

If you have opinions on how best to paint this bikeshed, this PR is the place to speak up. Once this is merged I'd like to change style config as rarely as possible because it's distracting churn when reading through history during bughunts. Speak now or forever hold your peace or, in the future, make a compelling, metrics-driven argument that a style change will materially improve code quality.

The current 3,382 offenses may seem like a lot, but if you sort by offense count you'll of course see a [pareto-like distribution](https://en.wikipedia.org/wiki/Pareto_distribution) of 135 cops, so this PR hopefully won't linger for months. `rubocop | grep -o '[A-Z][^/]*/[A-Z][^ ]*' | sort | uniq -c | sort -rn | head -n 20`

TODO: run rubocop as part of the test suite so humans see it easily and Travis fails the build.

### CODE REVIEW

**Comment by talklittle** [comment]
:+1: makes sense

On a related note, given the automated checks being added to the repo, maybe maintainers could refrain from committing non-critical changes directly to `master` in the future, so they'll be subject to automated checks on their pull requests as well? :wink:

**Comment by hmadison** [comment]
This looks good to me.

**Comment by jcs** [comment]
I don't really care about this code anymore so do whatever you want, but:

> Like everybody I have opinions on style issues, but my preferred style for any codebase is whatever the codebase is already doing.

I think I was/am pretty consistent in my code style but most of this diff changes the style, not the code to conform to the existing style as you said.

    -    new_tags.keep_if {|t| t.valid_for? @user }
    +    new_tags.keep_if { |t| t.valid_for? @user }
 
All of the existing code uses `{|`, so how is `{ |` considered the existing style?

    $ fgrep -r -- '{|' app | wc -l 
          51
    $ fgrep -r -- '{ |' app | wc -l
           0

Similarly for spaces around brackets in array declarations.

**Comment by pushcx** [comment]
I didn't notice the codebase was consistent. I haven't seen another do it so it looks odd to me. I put no thought into that one, I autocorrected it and moved on.

**Comment by pushcx** [comment]
As described, I've edited 1ea897a into b1f83f5 to remove the space between block curly braces and arguments.

**Comment by pushcx** [comment]
As I'm getting into the `Rails` cops a number of them are new Rails idioms, like `find_by` in place of `where().first`. I'm going to adopt most of these as they're not especially invasive.

**Comment by pushcx** [comment]
OK, no cops complaining and the merge conflicts are trivial. I'll merge Wednesday morning, if anyone wants to express an opinion before then.

**Comment by sean-public** [comment]
Since this touches so many files, I imagine anyone working in a branch will need to rebase. Is there any such work going on and should anyone be notified in particular to make sure they see this mega-merge incoming?

image

**Comment by talklittle** [comment]
Good point, @sean-public -- would be nice to get outstanding PRs merged first, so the authors won't be forced to conform to style checks that didn't exist when they initially created the PRs.

**Comment by pushcx** [comment]
I merged the open PRs that were ready to go.

**Comment by pushcx** [comment]
OK, and merged this branch down, too.

**Pull request merged**
