### PR TITLE
Update to Rails7.2

### PR DESCRIPTION
**Pull request by cpgo**
Saw this issue https://github.com/lobsters/lobsters/issues/1311 and was curious how hard the upgrade was gonna be.
Just updated `database_cleaner` and `activerecord-typedstore`
Tests passed locally but haven't tried the application yet

### CODE REVIEW

**Comment by MatheusRich** [comment]
One thing to be aware of is that 7.2 has a new default config that requires users to have modern browsers. Take this into consideration.

**Comment by pushcx** [comment]
@MatheusRich Could you elaborate on that? I don't spot anything with a skim of [the release notes](https://guides.rubyonrails.org/7_2_release_notes.html).

**Comment by pushcx** [comment]
This test failure is irrelevant; I'll push a fix in a few minutes and re-run.

**Comment by MatheusRich** [comment]
@pushcx sure thing. It's [this section](https://edgeguides.rubyonrails.org/7_2_release_notes.html#add-browser-version-guard-by-default). Here's what they say:

> This means that all other unknown browsers, as well as agents that aren't reporting a user-agent header, will be allowed access.
> 
> A browser that's blocked will by default be served the file in public/406-unsupported-browser.html with a HTTP status code of "406 Not Acceptable".

And in the code example:

```ruby
class ApplicationController < ActionController::Base
  # Allow only browsers natively supporting webp images, web push, badges, import maps, CSS nesting + :has
  allow_browser versions: :modern
end
```

But fully reading the text I see:

> **Newly generated applications have this guard set in `ApplicationController`.**


So this only applies to newly generated apps. My bad!!!

**Comment by pushcx** [comment]
[Background](https://github.com/rails/rails/pull/50467).

That is fundamentally opposed to the way this codebase works, progressive enhancement, and the longevity of websites. I would never enable or support it.

**Comment by MatheusRich** [comment]
Yes, that why I wanted to give a heads up. I thought that was enabled by default on 7.2

**Comment by cpgo** [comment]
Not that I took a better look at the open PR's I believe we should close this one in favor of [#1316](https://github.com/lobsters/lobsters/pull/1316) as it seems more complete.

**Pull request closed without merging**
