### PR TITLE
Allow for deletion of System messages (#946)

### PR DESCRIPTION
**Pull request by dracconi**
Makes the `author` of a message optional and delegates the check to a special
function (`is_authored?`) in the `message` model. It checks whether the author
exists, or, if the message is deleted and the author's id is 0.
Includes the tests for that behaviour.

Side note: Haven't tested if it runs.

### CODE REVIEW

**Comment by dracconi** [comment]
Eh forgot a colon and broke that... Sorry... I'll resubmit..

**Comment by dracconi** [comment]
After long hours of CI based development, maybe it will _finally_ pass.

**Comment by pushcx** [comment]
Thanks for fixing this bug. I've fixed the conflicts introduced by standardrb and am merging.

**Comment by pushcx** [comment]
I spent a minute tinkering with these test failures and... uh, the code works without it. I'm not sure what changed here to fix it. I'm sorry your PR was wasted.

**Pull request closed without merging**
