### PR TITLE
Rails 6

### PR DESCRIPTION
**Pull request by thomasdziedzic**
The release notes can be found at https://guides.rubyonrails.org/6_0_release_notes.html

# Requires
- [x] production to be running ruby 2.5.1

# Post Upgrade
1. https://github.com/lobsters/lobsters/issues/724 to enable new defaults

### CODE REVIEW

**Comment by pushcx** [comment]
Thanks for taking on another major version update! Looks like a great reason to take the Ruby + Ubuntu updates off the backburner.

**Comment by thomasdziedzic** [comment]
> Looks like a great reason to take the Ruby + Ubuntu updates off the backburner.

Is the work for this tracked at https://github.com/lobsters/lobsters-ansible/issues/22 ?

If so, are there any bite sized tasks I can help out with or is this just something the admin needs to take care of? I'm not familiar with ansible, but I'm pretty familiar with chef so probably some of those skills can translate a bit to ansible I hope.

**Comment by pushcx** [comment]
Ah, you're ahead of me and you already saw that we've updated to Ruby 2.7. I was going to come talk about getting this out of the backlog, thanks for being ahead of me.

I see how this is blocked on #863 - I'm going to do a pass through other PRs tonight but that's a high-priority bug for me, and I'll get to it soon if nobody beats me to it.

**Comment by thomasdziedzic** [comment]
Now that https://github.com/lobsters/lobsters/issues/863 is fixed, and the prerequisite of having ruby >= 2.5 has been met, I think this branch is ready for review and merge.

I cleaned up the commits a bit so it's easier to follow them along.

Please review and let me know if you have any questions.

Thanks for your time.

**Comment by pushcx** [comment]
OK, the server has been updated for long enough that I feel confident that it's not going to surprise us with anything (well, at least anything related to Ruby or other big dependency updates). Let me give this a reread.

**Comment by pushcx** [comment]
This is really nice and short, how great. Looking at it locally... phew, I missed being able to see all the testing dots. I'm going to merge this down now, I don't see any tweaks needed.

Thanks again, Thomas. I appreciate you taking on these upgrades.

**Comment by thomasdziedzic** [comment]
No problem!

**Pull request merged**
