### PR TITLE
Add Lobsters dark mode

### PR DESCRIPTION
**Pull request by soc**
dark-mode

See #637.

### CODE REVIEW

**Comment by soc** [comment]
I couldn't verify whether the missing L in the red square was caused by these changes or is just a quirk in Firefox caused by using the Style Editor in combination with the Dark Website Forcer extension to develop this.

The color scheme are intentionally chosen very conservatively; the colors of tags and hats have been preserved.

**Comment by danielcompton** [comment]
I’m on board with this approach, but the contrast seems very low with these colours. I had previously started this, I’ll try and pull out my branch and the colours I used.

**Comment by soc** [comment]
> I’m on board with this approach, but the contrast seems very low with these colours.

The reduction of the contrast in the dark scheme is intentional, I believe it's part of the reason of having one. I'd propose negotiating the colors after we have dark mode and received some feedback.

> Another option is to add a CSS Postprocessor like PostCSS to add the non-var version of the light mode colours before the var version, e.g. https://github.com/MadLittleMods/postcss-css-variables. I’m not sure if the added complexity is worth it though, it would significantly complicate the build.

@pushcx Mentioned in the issue that it's not required.

**Comment by soc** [comment]
I pushed some refinements and better variable names.

**Comment by soc** [comment]
@pushcx Is there anything you'd like me to do, or is this good to go?

**Comment by pushcx** [comment]
Could you catch me up on what's happening between this PR and #847? I see your name on both, and if you and @soc have collaborated, can we combine these into one PR?

**Comment by soc** [comment]
From my point of view (which is just my personal opinion) I believe that dark modes are meant to be less eye-straining than the "light" mode – which is why the color theme I picked has reduced contrast.

I have been using roughly the same color scheme on my personal website for years and have received zero complaints about it being _too_ low contrast.

This is not to say that there won't be any complaints – but I think it would make sense to either pick @danielcompton's or my scheme and adjust it based on the specific criticism received after it has been introduced – instead of trying to find a compromise that makes no one happy in the end.

**Comment by pushcx** [comment]
I'm more concerned with making no one happy at the beginning - er, well, cutting down the chaos, really. Generally we avoid sinking into endless bikeshedding by not doing a lot of cosmetic changes, so a big visible change is going to prompt a round of distress at the change and likely heated arguments on tiny tweaks, or impractical schemes to make everything configurable that turn out to make everything expensive to maintain. If it's possible to do one round of that instead of two, that'd be a lot less stressful.

So I wondered if there's a fundamental difference between the two approaches worth talking about once up-front. Let's see what Daniel has to say about how he picked that set of colors. If these come down to personal preference, well, that's sometimes how it goes and I'll figure out how to cut the baby in half.

**Comment by soc** [comment]
I defined over 30 CSS variables that can be used to adjust both the light and the dark theme, so I think we are pretty close to making everything configurable already. (In the sense of people being able to drop their preferred CSS into their Stylus extension.) :-)

**Comment by danielcompton** [comment]
I approached my design with these goals:

* make the dark mode quite dark so the screen isn't too bright at night
* have a high contrast ratio for accessibility
* not change the feel too much from the light mode Lobsters theme

I used the light mode theme colours as the base and then inverted them or lightened them to fit the dark mode context.

**Comment by GarbageHamburger** [comment]
As mentioned on the IRC, this could also be implemented as an alternative stylesheet: https://developer.mozilla.org/en-US/docs/Web/CSS/Alternative_style_sheets

Note that as far as I know this only works for Firefox. However it's a nice alternative that does not require any use of Javascript to achieve.

**Comment by pushcx** [comment]
@GarbageHamburger This PR also doesn't require JS.

@soc I hope you are prepared for folks to show up to help paint this bikeshed, because I'm going to merge this and push it live. Thanks for contributing it. :D

**Comment by pushcx** [comment]
Firefox has announced UI for dev support: https://twitter.com/FirefoxDevTools/status/1359896019757113344

I'm unaware of the state of tooling around css variables, but this may be worth picking back up after Firefox 87.

**Pull request merged**
