### PR TITLE
filter by tag and domain when searching for comments

### PR DESCRIPTION
**Pull request by david-wolgemuth**
Fix to issue [#491 Comment search doesn't use tag/domain scope.](https://github.com/lobsters/lobsters/issues/491).

### CODE REVIEW

**Comment by pushcx** [comment]
Any followers: there was significant discussion of this over in #502 and some offline discussion between David and I setting to redesign `Story.domain` and searching. This PR will change significantly (or just be closed + replaced, if making a new branch looks easier to David) before merging.

**Comment by pushcx** [comment]
David - any chance you're settled in your new gig and want to take a run at an exciting merge conflict to add these tests?

**Comment by david-wolgemuth** [comment]
😄 Sorry I totally forgot I had this open issue!  I'll get on it tonight

**Comment by david-wolgemuth** [comment]
@pushcx - rebased on master!

I added `gem "rb-readline"` to the development/test group to fix a byebug issue.  I think it might have been introduced during the rails upgrade?

**Comment by pushcx** [comment]
Cool, thanks for these tests!

**Pull request merged**
