### PR TITLE
Update message.rb

### PR DESCRIPTION
**Pull request by jwjwyoung**
make find_by username is case insensitive

### CODE REVIEW

**Comment by briankung** [comment]
See comment here: https://github.com/lobsters/lobsters/pull/673#discussion_r280587856

Basically, from my reading of the extant code, the username and email fields are case insensitive MySQL columns, so `#where` clauses will return case insensitive, anyway. I've also manually tested this and found it to be case insensitive with usernames.

**Comment by jwjwyoung** [comment]
Thanks for your reply, again I need to say it's okay under MySQL, but not works well under PostgreSQL,  as discussed in https://github.com/lobsters/lobsters/issues/670.

**Comment by briankung** [comment]
Ah, my bad! ✌️

**Comment by pushcx** [comment]
After [discussion in the other PR](https://github.com/lobsters/lobsters/pull/673#issuecomment-496917141), we're going to take a different strategy.

**Pull request closed without merging**
