### PR TITLE
Support looking up all stories by their URL.

### PR DESCRIPTION
**Pull request by nogweii**
This needs tests, but is a start.

You can test the new endpoint locally with `curl`:

    curl -isSL "http://localhost:3000/stories/all?url=https://example.com"

### CODE REVIEW

**Comment by nogweii** [comment]
By the way, how do you get the lorem ipsum generated content? Running `rake db:seed` fails for me locally, complaining about the email already being used.

**Comment by pushcx** [comment]
`rails fake_data` - if it's not in the readme or not clear, you can paint that fence too :D

**Comment by nogweii** [comment]
> rails fake_data - if it's not in the readme or not clear, you can paint that fence too :D

Whoops, it was in the README. I only read CONTRIBUTING. :sweat_smile:

**Comment by pushcx** [comment]
I pinged you in #1304 that I wrote up after the stream, but I wanted to link it so you can see that I had some URL plans and a liiiitle more functionality. Can I talk you into adding those things, or would you like to hand off the PR and I'll finish?

**Comment by nogweii** [comment]
Sweet, all of those features makes sense. I'll add them to this PR.

**Comment by pushcx** [comment]
Awesome, thank you.

If you need it, the command I use to "run the build" in dev is: `bundle exec rspec && bundle exec standardrb --fix-unsafely && brakeman -q`

**Comment by nogweii** [comment]
Updated the code, now split into a separate controller. But I'm failing to make rspec tests. I could use some help with writing them; maybe an activity for next Tuesday?

**Comment by pushcx** [comment]
Happy to help, rspec leans hard into being a DSL so it has a pretty steep learning curve. Did you maybe mean Mondays or Thursdays when I'm scheduled to stream? Either works for me. I'm pretty busy this upcoming Tuesday.

**Comment by pushcx** [comment]
I've [updated CONTRIBUTING.md](https://github.com/lobsters/lobsters/commit/484ed4970d40b1732746b6e3acfa8c43db0bcd7f) based on the conversations we've had in your PRs. Thanks for the reminder, this was long overdue.

**Comment by pushcx** [comment]
@nogweii I put this on my notes for this afternoon's stream, but no worries if you can't make it, I have plenty of bugs to spend time on. :smile: 

Also, I added Twitch chat to the transcript on my archive pages and I got a good laugh out of [this interaction](https://push.cx/stream/2024-08-15-a-healthy-amount-of-bugs#t00-29-07) we had.

**Comment by pushcx** [comment]
Thanks for adding this feature!

**Pull request merged**
