### PR TITLE
Exposing most pages as JSON and RSS

### PR DESCRIPTION
**Pull request by NinjaTrappeur**
Hi,

This PR expose most of lobsters routes as HTML, JSON and RSS. I basically just added both the JSON and RSS formatters to every relevant routes. I haven't modified those for which the HTML formatter is not the default one.

Note: I did not refactored the routes, a lot of legacy/duplicate one seems to still be present.

I needed to test this change locally and had some trouble setting up the project on my system. I added a shell.nix file which will help future nix users to setup their dev environment and prevent most of the struggles I gone though.

### CODE REVIEW

**Comment by pushcx** [comment]
Hey, thanks for taking a look at the source of some 404s. The last time this came up I wrote up issue #482 to remove the html `scope` to remove all the workaround `:format`s, rather than add more of them. Did you try that and get some kind of failure out of it?

As for nix - I don't mind adding it, but (like the Vagrantfile) I don't use it to know how to maintain it and would expect it to break when we update Ubuntu for the new version of Ruby. Maybe add a warning?

**Comment by NinjaTrappeur** [comment]
No, this is actually the first time I ever write ruby, I was a bit
afraid of breaking anything :).

I'll have a look at this scope by the end of the week. I'll also add a
warning as well as my handle on the shell.nix file.

On Tue, May 8, 2018, at 21:09, Peter Bhat Harkins wrote:
> Hey, thanks for taking a look at the source of some 404s. The last
> time this came up I wrote up issue #482[1] to remove the html scope to
> remove all the workaround :formats, rather than add more of them. Did
> you try that and get some kind of failure out of it?> As for nix - I don't mind adding it, but (like the Vagrantfile) I
> don't use it to know how to maintain it and would expect it to break
> when we update Ubuntu for the new version of Ruby. Maybe add a
> warning?> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[2], or mute the thread[3].> 


Links:

  1. https://github.com/lobsters/lobsters/issues/482
  2. https://github.com/lobsters/lobsters/pull/490#issuecomment-387510180

**Comment by NinjaTrappeur** [comment]
So, I just made a bit of archeology in the git logs :)

The html scope has been here for a long time, actually since 981759c34ff6eeb629b0cb54b029b1fc0001a611 (log: "be explicit about which route formats are accepted). There hasn't been any major rewrite of the routes since then. The commit you mentionned in #482 was actually just a revert which confused git somehow. The html scope was already there.

I guess we could add json and rss to all the routes, but, according my very limited understanding of rails, we still need to implement these renderers in the controllers.

Some controllers seems to be already implementing those formats even though they were not exposed on the routes. For instance, the /upvoted json and rss controller renderers have been introduced in ab8f8f3a , but it seems like the author forgot to add the associated routes.

So here's a potential plan:

1. Check I did not screw things up: check the controllers of the routes I exposed JSON and RSS for are actually handling those formats. Then we could merge this PR: I need the paginated /newest data.
2. On another PR, check we can safely write json formatted for the POST actions. I did not modified these routes in this PR.
3. On arother PR, check the duplicate routes and see if we can decommission them: the routing scheme seems a bit messy.

**Comment by pushcx** [comment]
Thanks for digging in, this gave me the confidence to tackle #482. I ran `rails routes > pre`, removed the scope, and ran `rails routes > post`. Diffing the two files showed the only thing that changed was the removal of the redundant `format` on the routes.

**Comment by NinjaTrappeur** [comment]
Nice! Thanks.

**Pull request closed without merging**
