### PR TITLE
Add Skylight instrumentation

### LINKED ISSUE #454: Skylight Instrumentation
Hello!

I work at [Skylight](https://www.skylight.io/). We are launching a [program](https://www.skylight.io/oss) to offer free Skylight accounts to open source apps (similar to Github and Travis), so I am reaching out to see if this is something you would be interested in.

If you’re not already familiar with Skylight, it is a smart profiler for Rails apps. Skylight makes it easy to pinpoint performance issues in Rails applications.

We work on a lot of open source projects ourselves, and in our experience it can be pretty hard to get contributors to work on application performance issues. Few contributors consider working on performance problems, and the ones that might be interested may not even know where to start. By making performance information more accessible, we hope to inspire potential contributors to tackle slow parts of your app, and have a good way to see if their contributions helped.

For reference, this is the [Skylight dashboard](https://oss.skylight.io/app/applications/g0gJSNnzYAws/) we set up for [The Odin Project](https://www.theodinproject.com/). It should give you a pretty good idea of how Skylight works.

Integrating Skylight to a Rails application is very easy. All you have to do is add the gem to your Gemfile and set an environment variable with your authentication token. (We are happy to send a pull request.) If you’re interested in setting this up or if you have any questions, you can reach us here or at [support@skylight.io](mailto:support@skylight.io).

We'd also love to feature you on our [website](https://www.skylight.io/oss) as one of the first open source organizations using Skylight. We hope you’ll join us in helping to make performance an accessible way to contribute to an open source project!

### PR DESCRIPTION
**Pull request by chancancode**
Closes #454

Skylight dashboard URL: https://oss.skylight.io/app/applications/UVOwCQJiWlFy

The dashboard is public, so any (potential) contributors will be able to access it without creating a Skylight account.

It currently doesn't have data yet, I will need to work with @pushcx to add an environment variable on production. I'll email the details off-thread (I sent it to your Git email, I hope that's okay).

### CODE REVIEW

**Comment by chancancode** [comment]
Forgot to mention, I ran into the same problem that @jamesbrink ran into, so I cherry-picked that commit

**Comment by chancancode** [comment]
@pushcx friendly ping 😀 let me know if there is anything I can help with moving this forward

**Comment by pushcx** [comment]
I'm pushing this live now and will keep an eye on the dashboard to hopefully see data arriving shortly.

**Comment by pushcx** [comment]
@chancancode Doesn't look like data's arriving. I saw the note about exiting and fresh-staring a new unicorn process and that doesn't seem to have helped. (And yes, the app is running in production environment on a supported Ruby version and Linux server.)

Please set me as the owner for the Skylight project.

The "open source" link on [the app page](https://www.skylight.io/app/applications/UVOwCQJiWlFy/recent/5m/endpoints) is broken in an interesting way: it opens a new tab to the same page where I have a "Sign Up for Skylight" button instead of an indication that I'm logged in.

**Pull request merged**
