### PR TITLE
Add username to exception notifications

### LINKED ISSUE #676: Add username to exception notifications
I get exception notifications by email. The request includes a user's `session_token` and I use this to look up affected users and PM them, but it'd be convenient if username of the currently logged-in user could appear directly.

### PR DESCRIPTION
**Pull request by drakmail**
Add username to exception_notifications (fixes #676)

### CODE REVIEW

**Comment by drakmail** [comment]
@pushcx 👌Did it.

**Comment by Carpetsmoker** [comment]
You should probably fix the Rubocop error:

```
Offenses:
app/controllers/application_controller.rb:144:17: C: Style/DisallowSafeNavigation: Do not use &.
      username: @user&.username,
                ^^^^^^^^^^^^^^^
```

For example (untested):

```
def prepare_exception_notifier
  return if @user.nil?
  request.env["exception_notifier.exception_data"] = {
    username: @user.username,
  }
end
```

**Comment by drakmail** [comment]
@Carpetsmoker oh, I'm forgot to commit 🤦‍♂

**Comment by pushcx** [comment]
Thanks for this! I hope I never see another prod exception and it's useless... but really, I'm going to see it in the next couple weeks and appreciate it. :D

**Pull request merged**
