### PR TITLE
Add JSON MIME to StoriesController#check_url_dupe

### PR DESCRIPTION
**Pull request by theoretick**
Replacement for https://github.com/lobsters/lobsters/pull/555

Adds JSON support to the `check_url_dupe` endpoint allowing searches for discussions about previously submitted URLs.

### CODE REVIEW

**Comment by pushcx** [comment]
Solid PR. Glad to support your site so easily.

**Comment by pushcx** [comment]
(BTW, if you're looking tonight, I'm not deploying until tomorrow morning with some other stuff.)

**Comment by theoretick** [comment]
@pushcx 🙌 awesome thanks for the suggestion and the merge! Happy to contribute

**Comment by theoretick** [comment]
@pushcx of course now that this is live I realize I overlooked the authentication issue. Would you accept an additional change to drop `check_url_dupe` from the logged-in requirement? If so, please see related: https://github.com/lobsters/lobsters/pull/595

**Pull request merged**
