### PR TITLE
Make merged votes voteable

### LINKED ISSUE #424: User's own comments from merged stories don't show own vote
https://lobste.rs/s/dwzplh/krack_attacks_breaking_wpa2#c_varrat

Probably just need a tweak to whatever query pulls in the comments of a merged story. This doesn't allow people to vote multiple times, it's just a data fetching + display issue.

### PR DESCRIPTION
**Pull request by evexoio**
Fixes #424 and #500

### CODE REVIEW

**Comment by pushcx** [comment]
Can I talk you into writing a test? We've had a couple similar issues over the years, I'd like to make sure this bug doesn't creep back into the codebase. It'll have to be a feature test: create a story with a comment, have a user upvote the comment, merge that story into a new story, confirm that looking at the merged story shows the comment with the `upvoted` class. I don't think #500 is a separate enough issue it requires an independent test.

**Comment by evexoio** [comment]
@pushcx Sure, welcome back 🎉

**Comment by evexoio** [comment]
@pushcx This is ready for review, I just pushed the tests.

**Comment by pushcx** [comment]
Thanks for adding a test. I'm merging this down so I can deploy it now, but I'm curious: what happened that you had to edit `stub_login_as`?

**Comment by pushcx** [comment]
Ah, yeah, I see how that breaks down with two users. I read the test and didn't make the connection.

Again, thanks for your contributions. I've been watching the server + chat room this morning after deploying this and the form changes and we've had zero issues, which is nice for such a complicated pair of issues and a wide-ranging code change.

**Comment by evexoio** [comment]
@pushcx Nice! that's great  🎉🎉🎉

thanks for letting me know :)

**Pull request merged**
