### PR TITLE
integrate rubocop-disallow-safe-navigation

### PR DESCRIPTION
**Pull request by tansengming**
This finishes https://github.com/lobsters/lobsters/issues/596 by integrating a new custom Rubocop Cop to check for the safe navigation operator. Let me know what you think!

### CODE REVIEW

**Comment by tansengming** [comment]
Note that I had to fix a `&.` problem for travis to pass 
https://github.com/lobsters/lobsters/pull/598/commits/cf9fdaf04df09812a67af15cc87d059f9984f894 so I guess that means it's working 😸

**Comment by pushcx** [comment]
Did this strictly require a new, custom gem? I'd really prefer to avoid that. I'd hoped with `require` we could pull in the cop from this repo's `extras/` directory.

**Comment by tansengming** [comment]
>  I'd really prefer to avoid that. I'd hoped with require we could pull in the cop from this repo's extras/ directory.

@pushcx I've updated the PR for this.

**Comment by pushcx** [comment]
This is great, thank you. I hadn't realized `&.` had snuck in, so I'm glad to have rubocop guarding the door from now on.

**Pull request merged**
