### PR TITLE
Upgrade Ruby to version 2.5.1

### PR DESCRIPTION
**Pull request by ur5us**
Ruby 2.5.1 is the default version shipped with Ubuntu 18.04 LTS.

Effectively, this PR supersedes https://github.com/lobsters/lobsters/pull/410.

### CODE REVIEW

**Comment by pushcx** [comment]
Waiting on https://github.com/lobsters/lobsters-ansible/issues/22

**Comment by pushcx** [comment]
Any idea why rubocop decided to start complaining? I'm about to bump it with some other gems, but the CI build looks like some novel cops to disable.

**Comment by ur5us** [comment]
@pushcx Upgrading to newer versions of Ruby sometimes activates new cops due to new syntax and/or standard library additions. Looking at the build output it confirms what I just said:

```
Use match? instead of match when MatchData is not used.
```

`String#match?` is new in Ruby 2.5 IIRC. I’m happy to clean that up.

**Comment by pushcx** [comment]
Ah, I didn't realize some of them were gated on Ruby versions. Might as well update to the new feature for the performance nudge, yeah.

**Comment by ur5us** [comment]
@pushcx Should be all good to go whenever you’re ready to roll out Ruby 2.5.x :)

**Comment by thomasdziedzic-pd** [comment]
Any updates or eta? Asking because [Rails 6.0 will require ruby >= 2.5](https://medium.com/rubyinside/whats-coming-to-rails-6-0-8ec79eea66da)

**Comment by pushcx** [comment]
We're still blocked on https://github.com/lobsters/lobsters-ansible/issues/22.

**Comment by pushcx** [comment]
Better handled in https://github.com/lobsters/lobsters-ansible/issues/22

**Comment by ur5us** [comment]
@pushcx You may want to re-open this PR. It contains more than the upgrade of Ruby. The bulk of this PR fixes RuboCop issues which resulted in a broken build on CI if I remember correctly. Moreover, it looks like you’ll still need this PR if you’re going to go with the Ruby version packaged with [Ubuntu 18.04 LTS](https://packages.ubuntu.com/search?keywords=ruby&searchon=names&suite=bionic&section=all). lobsters/lobsters-ansible#22 will only take care of installing Ruby while this PR will enable it for committers (users of rbenv, RVM, etc). If the plan is to deploy rbenv or one of the other Ruby version managers via Ansible you might need a revised version of this PR with the correct Ruby version. It all depends on how exactly the app is deployed though.

**Comment by pushcx** [comment]
Ah, yep, you're right. I thought this was a PR I'd opened to bump the version that didn't touch anything else. Sorry for the confusion; I do look forward to this merge.

**Comment by pushcx** [comment]
We've bumped prod to ruby 2.7 and these fixes landed, though not simply as a merge. Thanks again for this help, you made the upgrade easier.

**Pull request closed without merging**
