### PR TITLE
Sponge: properly encode POST data

### LINKED ISSUE #1081: pushover notification truncated at '&'
I posted [a link](https://lobste.rs/s/dnfgez/using_windows_after_15_years_on_desktop) to lobste.rs and subscribed to notifications via pushover.

When [this comment](https://lobste.rs/s/dnfgez/using_windows_after_15_years_on_desktop#c_0b4bam) was posted, my notification read

```
> I am a software 
```

That was clearly truncated at the `&` in the comment. I'm not sure whether this is a lobste.rs thing or a pushover thing, but I do have a shell script that sends me notifications via pushover and I just confirmed that `&` doesn't cause those to be truncated.

### PR DESCRIPTION
**Pull request by jcs**
Should fix #1081

### CODE REVIEW

**Comment by pushcx** [comment]
Thanks for digging down into this one.

**Comment by pushcx** [comment]
@jcs I was watching this deploy when I realized what was nagging at me… does Pushover not like the escaping from `.to_query`? This code seems to do the same thing.

```
> puts({a: 1, b: [1, 2, 3], c: { d: 3 }}.to_query)
a=1&b%5B%5D=1&b%5B%5D=2&b%5B%5D=3&c%5Bd%5D=3

> puts CGI.unescape({a: 1, b: [1, 2, 3], c: { d: 3 }}.to_query)
a=1&b[]=1&b[]=2&b[]=3&c[d]=3
```

**Comment by jcs** [comment]
I didn't know about `to_query` and I just took that new code from one of my upstream projects using Sponge.  But if you want to replace it with `to_query`, Pushover should accept it just fine.

**Comment by hazycora** [comment]
this PR broke Mastodon posts: https://botsin.space/@lobsters/113229635168362904

**Comment by jcs** [comment]
The mastodon module is doing its own escaping which should no longer be needed.

https://github.com/lobsters/lobsters/blob/bd8638d6c215d5447a68f9fe84366d22e21e14ca/extras/mastodon.rb#L111

**Pull request merged**
