### PR TITLE
enable default_protect_from_forgery and use_authenticated_message_encryption

### PR DESCRIPTION
**Pull request by thomasdziedzic-pd**
https://github.com/lobsters/lobsters/issues/509

from http://guides.rubyonrails.org/configuring.html

> config.action_controller.default_protect_from_forgery determines
> whether forgery protection is added on ActionController:Base. This is
> false by default, but enabled when loading defaults for Rails 5.2.

rails pull request: https://github.com/rails/rails/issues/29193

### CODE REVIEW

**Comment by thomasdziedzic-pd** [comment]
I didn't know if I should remove the `protect_from_forgery` line at https://github.com/lobsters/lobsters/blob/master/app/controllers/application_controller.rb#L2 since it uses a different option.

The default is `:null_session` as explained here: http://api.rubyonrails.org/classes/ActionController/RequestForgeryProtection/ClassMethods.html#method-i-protect_from_forgery

But removing the line in the application controller would switch the method to `:exception` which is the default method generated in rails now.

Relevant docs:

> Valid unverified request handling methods are:
> 
> :exception - Raises ActionController::InvalidAuthenticityToken exception.
> 
> :reset_session - Resets the session.
> 
> :null_session - Provides an empty session during request but doesn't reset it completely. Used as default if :with option is not specified.

http://api.rubyonrails.org/classes/ActionController/RequestForgeryProtection/ClassMethods.html#method-i-protect_from_forgery for full details.

**Comment by thomasdziedzic-pd** [comment]
Added another commit which should enable use_authenticated_message_encryption. I realized that this can be safely enabled since lobsters doesn't use the MessageEncryptor class.

**Comment by thomasdziedzic-pd** [comment]
I opened a rails issue for the outdated configuration docs: https://github.com/rails/rails/issues/33170

**Comment by pushcx** [comment]
Hey @thomasdziedzic-pd, thanks for this one. I'm moving slowly on this one because it's security-sensitive and I haven't been able to schedule a couple distraction-free hours to give this the deliberative attention it deserves.

**Comment by thomasdziedzic** [comment]
Do you have any questions that I could help you out with this PR? Would like to continue working on some other things that are blocked by this PR

**Comment by pushcx** [comment]
Spent time this morning reading the docs and kicking the tires, looks good.

**Pull request merged**
