### PR TITLE
Fix git clone URL

### PR DESCRIPTION
**Pull request by nickhammond**
Update git clone url to the preferred github, git user style.

### CODE REVIEW

**Comment by pushcx** [comment]
I tested, it's not broken.

**Comment by nickhammond** [comment]
Weird, times out for me. No worries.

Looks like Github retired the unauthenticated git:// a while back https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git

```
➜  github time git clone git@github.com:lobsters/lobsters.git
Cloning into 'lobsters'...
remote: Enumerating objects: 19659, done.
remote: Counting objects: 100% (1779/1779), done.
remote: Compressing objects: 100% (761/761), done.
remote: Total 19659 (delta 1098), reused 1615 (delta 990), pack-reused 17880
Receiving objects: 100% (19659/19659), 5.90 MiB | 14.09 MiB/s, done.
Resolving deltas: 100% (13013/13013), done.
git clone git@github.com:lobsters/lobsters.git  0.43s user 0.20s system 38% cpu 1.608 total
```

```
➜  github time git clone git://github.com/lobsters/lobsters.git -v
Cloning into 'lobsters'...
Looking up github.com ... done.
Connecting to github.com (port 9418) ... fatal: unable to connect to github.com:
github.com[0: 140.82.114.3]: errno=Operation timed out

git clone git://github.com/lobsters/lobsters.git -v  0.01s user 0.02s system 0% cpu 1:15.03 total
```

**Comment by pushcx** [comment]
Ah, it worked for me because it picked up my credentials. I should merge this.

**Comment by pushcx** [comment]
Do you want to restore the branch? I saw you asking about hacktoberfest in the other issue.

**Comment by nickhammond** [comment]
I've restored the branch. Yah, I'm hoping to help out with a few other things this month with lobsters, cheers.

**Comment by pushcx** [comment]
Thanks for spotting this issue and PRing it, I look forward to more contributions. :)

**Pull request merged**
