### PR TITLE
Fix typo on about page

### PR DESCRIPTION
**Pull request by wezm**
Just a small typo fix I noticed when reading the About page this morning.

### CODE REVIEW

**Comment by alanpost** [comment]
Thank you @wezm. Ignore the continuous integration failure, it's happening on master too--we can't fix it without a database migration on production so we're waiting on performing that.

**Comment by alanpost** [comment]
Give us a bit to deploy this change to production. When your typofix came in I asked #lobsters on freenode for further copy-editing and am collecting that in PR #904.

**Comment by wezm** [comment]
Awesome, take your time. 🙂

**Comment by alanpost** [comment]
Your commit is live, thank you again for taking the time to submit a PR.

**Pull request merged**
