### PR TITLE
Allow gemini and gopher homepage URLs

### PR DESCRIPTION
**Pull request by illfygli**
I thought it would be nice to allow Gemini spaces and Gopher holes in the homepage field.

### CODE REVIEW

**Comment by KangOl** [comment]
It would be great to have a link to a http-proxy version of theses links.

And maybe also extract canonical link when a proxyed url is submitted (like https://lobste.rs/s/jnwzms/my_first_freebsd_port_castor_gemini)

**Comment by alternet0** [comment]
LGTM

**Comment by pushcx** [comment]
@illfygli Thanks for suggesting this, seems fun.

I agree with @KangOl's suggestion. Could you add a `(<a href="">proxy</a>)` if the protocol is `gemini` or `gopher`? I know very few users will have their browsers set up for those protocols (or want to immediately do so for an unknown link).

**Comment by illfygli** [comment]
I gave it a try. I'm very bad at this. :)

**Comment by pushcx** [comment]
Nope, I have to disagree, you've done nicely and I'm merging this.

**Pull request merged**
