### PR TITLE
search: add tag scoped search

### PR DESCRIPTION
**Pull request by pushups**
When searching for a story a user can include a single tag:<tag_name>
element which will limit the scope of the search to that tag name.

This works similarly to the domain:<domain_name> feature which
limits the scope of the search to stories from that domain.

Examples:
"tag:python django" as a search query will search for stories
tagged with the python tag which reference the word "django".

"tag:python" will return all of the stories tagged with python
in the search results - which is essentially the /t/python page
but you can now order by Newest or Points as well.

Technical details:
* Added query parsing at the beginning of the search
to set a tag_scope string.

* When a tag_scope is set the relation gets another where clause
for only the tags that match exactly that scope.

* Modified the relevance queries to use literal SQL for the select
statements and the ranked ordering. See: title_match_sql, etc.
When the query was limited to tags ActiveRecord was re-writing
it by substituting the ORDER clauses into the columns for selecting
and the 'AS rel_title' was getting dropped. This caused the query
to fail.

### CODE REVIEW

**Comment by pushups** [comment]
Forgot to mention that this is meant to address: https://github.com/lobsters/lobsters/issues/317

**Comment by pushcx** [comment]
This is solid and I hope to merge it soon. Thank you!

I do see two bugs related to multiple tags. Imagine there's a story "test story" tagged "foo" and "bar".

1. If I search for "test tag:foo", the story is correctly listed, but only shows the "foo" tag, not also "bar".
2. If I search for "test tag:foo tag:bar", it only searches for stories with the "bar" tag instead of stories tagged "foo" and "both".

It'd also be great to have a couple tests - one of the basic functionality and one of searching for two tags not turning up a story with only one, and any other behavior you think would be valuable.

**Comment by pushups** [comment]
@pushcx Thanks for taking a look at this! I'm working on the tests and bug fixes when I have some free time and hope to get it over to you probably in the next couple weeks.

**Comment by pushups** [comment]
@pushcx I think this is ready for another review when you get a chance. 
* Tests passed.
* I added search_spec.rb and a few tests for regular search behavior, and also the tag specific behavior.
* I fixed the issues you pointed out: 
1. All tags are now displayed correctly
1. Searching for `baz tag:foo tag:bar` gives you stories with `foo` and `bar` tags that include the term `baz`.

**Comment by pushcx** [comment]
I'm sorry I lost track of this PR. I'm glad to merge and deploy it. Thanks, @pushups!

**Comment by pushups** [comment]
@pushcx I'm really excited to use this feature. Thanks for merging it!

**Pull request merged**
