### PR TITLE
Feature: Add /stories JSON endpoint

### PR DESCRIPTION
**Pull request by theoretick**
Hey all, thanks for the awesome site!

I was looking for some JSON endpoints to enable searches across lobste.rs and found these previous discussions: https://github.com/lobsters/lobsters/issues/42, https://github.com/lobsters/lobsters/issues/361, https://github.com/lobsters/lobsters/issues/150. It looks like no progress has moved forward recently so I took a look and added a `/stories.{html|json}` endpoint.

I originally considering modifying the `SearchController` to support both MIME Types but treating stories as a RESTful resource felt more correct. In addition, I added some HTML handling to provide more intuitive access to endpoint as well: redirecting unscoped `/stories` requests to root and scoped `/stories?=q` requests to `/search`.

#### Additional Notes

 1. The behavior of `Search#page_count` seemed a bit odd when result sets were empty or nil, returning either 0 or 5. IMHO a page_count should always be a positive integer so I corrected that behavior and added some `Search` tests.
 2. The unscoped `/stories.json` endpoint requires a query param. This is mostly to keep things simple and avoid the additional questions of sort order, caching, etc... If this seems overly restrictive, happy to change it.
 3. I initially started writing a more fully-featured test that actually used `Search` but due to the way MySQL full text search works, `MATCH(..) AGAINST(..)` does not function inside of transactions :( (https://dev.mysql.com/doc/refman/5.6/en/innodb-fulltext-index.html#innodb-fulltext-index-transaction). This side-tracked me a bit into working on https://github.com/lobsters/lobsters/issues/422 but that’s quite a bit more involved to keep the queries reasonably optimized. TBD!
 4. As a result of (3), I’m not a huge fan of the mocked Search results in the new controller spec but it seems sufficient for now.
 5. Should these JSON endpoints (and the existing `stories/:id.json` endpoint) be documented anywhere? Would it be worth adding a page, API spec, or some section to the readme?

Let me know your thoughts!

### CODE REVIEW

**Comment by pushcx** [comment]
Thanks for jumping in. I'm curious, what prompted this? I'm asking because I'm not really sure why the site has json endpoints; I just skimmed down `application.js.erb` and none of our code uses it. I'm happy to help curious users read the site programmatically without scraping, my concern is the cost of maintaining something we don't need. I don't want to commit to maintaining code we don't use, especially the stability of quirks like whether an API with zero results has zero pages or one empty page.

I'd rather add json output to the SearchController: doing this in StoriesController duplicates that controller action. We'll never remember to update that if the logic changes. Our controllers are not particularly RESTful (one of those things I'd like to slowly improve as I have excuse to touch them), but I'd rather see new/create semantics around a many-fielded Search model than a very complicated interface to indexing Story models. Kinda heading into the weeds where I'm not sure there's a lot of semantic bang-for-the-buck.

How did `Search#page_count` return 5 when there's no results? Zero sounds like the correct answer when there are no pages, though I can see why you prefer 1.

For documentation, my first instinct is to say that I'd like the pagination cleanup of #394 first. Or json-api to normalize output. Maybe that's letting "perfect" get in the way of "good". And maybe if they're irregular and undocumented people won't expect too much from them. :)

**Comment by theoretick** [comment]
Thanks @pushcx!  Apologies for the late reply, been a bit busy :)

> Thanks for jumping in. I'm curious, what prompted this? I'm asking because I'm not really sure why the site has json endpoints; I just skimmed down application.js.erb and none of our code uses it. I'm happy to help curious users read the site programmatically without scraping, my concern is the cost of maintaining something we don't need. I don't want to commit to maintaining code we don't use, especially the stability of quirks like whether an API with zero results has zero pages or one empty page.

Totally fair points. My initial motivation came from an issue someone opened for one of my personal projects (https://github.com/theoretick/discuss-it/issues/86).  tl;dr - http://discussitapp.com is a search tool for finding online discussions across reddit, hackernews, slashdot, etc, and lobste.rs would be an awesome addition.

When I initially started looking into this I figured I would have to scrape the site and I wasn’t really a fan of that approach so I took a look at a more programmatic solution. creating an entire API seemed to be going down a pretty big path as you noted, but I realized that there was already some initial JSON support [via the `StoriesController#show` action](https://github.com/lobsters/lobsters/blob/b43a5999b4b2140971ddc48dc5221f512e112e4d/app/controllers/stories_controller.rb#L167). As such, it seemed like an additional endpoint would be gradual enough to not be dumping too much complexity.

That said, I completely understand the added maintenance cost. Especially if it results in a significant change in semantics (see below). If after this discussion it seems like a bad direction, we can close this PR out. No worries at all :)

> I'd rather add json output to the SearchController: doing this in StoriesController duplicates that controller action. We'll never remember to update that if the logic changes. Our controllers are not particularly RESTful (one of those things I'd like to slowly improve as I have excuse to touch them), but I'd rather see new/create semantics around a many-fielded Search model than a very complicated interface to indexing Story models. Kinda heading into the weeds where I'm not sure there's a lot of semantic bang-for-the-buck.

👍 I took that initial approach but changed my mind. Happy to add a simpler `format.json { ... }` and keep it simple. One less controller!

The only issue I had is that it gets a bit weird to return different resource types through the same endpoint (i.e. stories vs comments). Perhaps nesting the resources in the response could be the most flexible so if we wanted to ever return both matching stories and comments it would be simple:

```
200 OK

{
  “stories”: [ ... ],
  “comments”: [ ... ],
  “meta”: {
  }
}
```

> How did Search#page_count return 5 when there's no results? Zero sounds like the correct answer when there are no pages, though I can see why you prefer 1.

The 5 count was an interesting one. So the way the logic appears to work, if `total` results is -1, then `total = max_matches` (100). Then the page count is calculated as `((total - 1) / per_page) + 1` or `((100 - 1) / 20) + 1` resulting in 5. See relevant logic: https://github.com/lobsters/lobsters/blob/b43a5999b4b2140971ddc48dc5221f512e112e4d/app/models/search.rb#L40-L44

RE: zero counts, I’d argue that returning a result set at all is enforcing a minimum page_count of 1. From an API perspective, the alternative would be a 404 condition where there is no idea of a page_count. From a service perspective (i.e. `Search` here), a page_count is a virtual attribute of the `results`, which is always an empty array: https://github.com/lobsters/lobsters/blob/b43a5999b4b2140971ddc48dc5221f512e112e4d/app/models/search.rb#L21. I’d probably feel differently if the result sets was nullified.  Regardless, that’s my 2 cents, if you’d prefer 0, I’m happy to change it.


> For documentation, my first instinct is to say that I'd like the pagination cleanup of #394 first. Or json-api to normalize output. Maybe that's letting "perfect" get in the way of "good". And maybe if they're irregular and undocumented people won't expect too much from them. :)

Hah, that one is always a tough call but think it really falls to the discretion of the maintainers. I'm all for iterative solutions but public documentation of an API brings up a non-trivial maintenance cost as you noted before.

Cheers,
Lucas

**Comment by pushcx** [comment]
No worries on the slow response; I tend to check in on the codebase on Wed + Thu mornings rather than throughout the week.

From poking around your app, it sounds like what would really fit your needs is an endpoint that takes a URL and returns a list of links to submissions of that URL, rather than an interface to the full search engine. The full-text search engine is the slowest, most resource-intensive database query on the site and I hesitate to encourage people to hit it in a loop - but url, hey, we have an index on that column, that's really cheap. I wouldn't even bother with pagination: the most-submitted link talk has only been submitted four times (Bret Victor's "The Future of Programming") and even if listing five hundred pairs of title + url this would be a cheap endpoint to serve. The natural place to put this would be `StoriesController#check_url_dupe`. There's some related work happening now in #557, even.

**Comment by pushcx** [comment]
#557 was implemented yesterday, so now is a good time to looking at making the `check_url_dupe` endpoint serve json. It looks like a really good fit for your needs.

**Comment by theoretick** [comment]
@pushcx thanks! Just opened https://github.com/lobsters/lobsters/pull/594 as a potential replacement and closing this one out

**Pull request closed without merging**
