### PR TITLE
escape repeated hyphens in user mentions (issues 1037)

### PR DESCRIPTION
**Pull request by fpsvogel**
This addresses #1037 

This is my first PR, so just let me know if you'd like me to change anything. Thanks!

### CODE REVIEW

**Comment by pushcx** [comment]
I'm going to close this PR in favor of the approach I described over here: https://github.com/lobsters/lobsters/issues/1037#issuecomment-1018116906

There's been some history churn for branches, so it's probably easier for you to re-fork the repo. I'm sorry for giving you a hassle as a first-time contributor.

**Comment by fpsvogel** [comment]
@pushcx That's OK! I really appreciated your feedback.

**Comment by pushcx** [comment]
Thanks. And to be real explicit - I don't mean to imply that I want to fix it; if you're interested in the AST approach I'd certainly appreciate a PR.

**Comment by fpsvogel** [comment]
@pushcx Yep, I'd understood that and I should've said I was already writing about my next attempt in the issue: https://github.com/lobsters/lobsters/issues/1037#issuecomment-1023734379.

**Pull request closed without merging**
