### PR TITLE
remove unused CSS rules

### PR DESCRIPTION
**Pull request by bovarysme**
As discussed in #640.

The `div#hat_holder` and `img#party_hat` rules are defined in the [`lobsters-ansible`](https://github.com/lobsters/lobsters-ansible/blob/master/roles/lobsters/files/app/assets/stylesheets/local/lobsters.css) repository. Would you like me to open a PR there as well?

### CODE REVIEW

**Comment by alanpost** [comment]
Your find brings to mind another ticket where we have files split between lobsters.git and lobsters-ansible.git.  There we considered moving stuff from lobsters-ansible.git to lobsters.git:

https://github.com/lobsters/lobsters/pull/576#issuecomment-436626449

**Comment by pushcx** [comment]
Thanks, @bovarysme, for researching this and figuring out what we can safely clean up. I'm really happy to merge this down.

This was the kick in the butt I needed to get that file history merged over; I'll remove those two rules myself.

**Comment by bovarysme** [comment]
The pleasure is mine! I've been browsing Lobsters daily for more than a year now, and I'm glad I can finally give something back. Thanks to you two for hosting and managing the site.

**Comment by pushcx** [comment]
I don't see a user account named 'bovarysme' - if you don't have one under any name, let me know what email I can send one to. (Twitter DM, Freenode, or email my first name @push.cx).

**Pull request merged**
